[RFR] Prevent the move wrong tile error
marmelab/15-puzzle-web pull request #9
Opened 2017-11-09 10:47 UTC by Luwangel

- [x] Catch the api error and do nothing after a not possible move

2017-11-09 11:02 UTC, jdemangeon commented on app/src/Api/GameApi.php
>    public function move(Game $game, int $tile) : Game {
Do you have a corresponding test?

2017-11-09 14:14 UTC, alexisjanvier commented on app/src/Api/GameApi.php
> +      return $game;
so the user doesn't see that there was an error?

2017-11-10 10:12 UTC, alexisjanvier commented on app/src/Api/GameApi.php
> +      return $game;
IMO, you should display something like "You can't move that tile. Try another one".

2017-11-10 10:14 UTC, alexisjanvier requested changes
Missing a test and error message

2017-11-10 15:44 UTC, alexisjanvier approved these changes

2017-11-10 15:44 UTC, merged